###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSZW5keSIsImVtYWlsIjoiRW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzI0NzU3MDcxLCJleHAiOjE3MjQ3NTcwODZ9.Lx-2-A8JaIfN42iTu1lkAPhD61NX_M8M8VHHmB5KwaY


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Rendy",
    "email": "Email@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Email@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE  http://localhost:5000/logout
